### PR TITLE
Text Highlight(Search)

### PR DESCRIPTION
**Pull request by TimTemi**
Functionality to search for a particular text in the entire pdf.

# Pull Request Template

**script name** -

**What have you Changed**

what you changed in the codebase.write here

### Self Check(Tick After Making pull Request)

- [x] This issue was assigned to me.
- [x] One Change in one Pull Request
- [x] My file is in proper folder
- [x] I am following clean code and Documentation and my code is well linted with flake8.
- [x] I have added README.md and requirements.txt with my script

If issue was not assigned to you Please don't make a PR. It will marked as invalid.

Join Us on Discord:- https://discord.gg/JfbK3bS

### CODE REVIEW

**Review by codeperfectplus — CHANGES_REQUESTED** [review]
Your code doesn't make any sense you are calling the re. search after main function. 
Try to create a separate file and run your code alone with the codebase. don't use __name__ __main__. we are importing it as module.

**Comment by TimTemi** [comment]
I have made changes

**Review by codeperfectplus — APPROVED** [review]

**Comment by codeperfectplus** [comment]
@DrakeEntity Please review it once.

**Comment by DrakeEntity** [comment]
why do we need to use the search function on pdf only? we are creating a common JSON book format. That function should apply to json_book. @codePerfectPlus

**Pull request closed without merging**
