### PR TITLE
Feature: ODT files support for audiobook as mentioned in issues

### LINKED ISSUE #46: support: ODT file support adding
**Is your feature request related to a problem? Please describe.**

Audiobook doesn't support ODT file format yet. So creating a feature request for ODT file request. A file with the “.odt” extension is an OpenOffice Document file. It's a common file type in Linux.

@DrakeEntity

### PR DESCRIPTION
**Pull request by Mr-vabs**
# Pull Request Template

**script name** -

**What have you Changed**

what you changed in the codebase.write here

I've added support for ODT files. I've tested and it's working fine. In order to make it supported, I've coded in `main.py` for file format , `utils.py` for actual logic, and required changes as in `requirements.txt`.

### Self Check(Tick After Making pull Request)

- [x] This issue was assigned to me.
- [x] One Change in one Pull Request
- [x] My file is in proper folder
- [x] I am following clean code and Documentation and my code is well linted with flake8.
- [ ] I have added README.md and requirements.txt with my script

If issue was not assigned to you Please don't make a PR. It will marked as invalid.

Join Us on Discord:- https://discord.gg/JfbK3bS

### CODE REVIEW

**Comment by DrakeEntity** [comment]
@Mr-vabs There are some bugs in your code. Please try to fix them

**Comment by DrakeEntity** [comment]
you can find more details in the code analysis workflow. we have implemented some code analysis work flow for clean and quality code.

**Comment by hot9cups** [comment]
Refer to [this](https://app.codacy.com/gh/Py-Contributors/AudioBook/pullRequest?prid=10418379) and [this](https://github.com/Py-Contributors/AudioBook/actions/runs/3303037027/jobs/5450537276) to locate your bugs and fix them.
You could also try and setup flake8 locally to have avoided the linting errors even before having raised the PR.

**Review by hot9cups — CHANGES_REQUESTED** [review]
Refer to [this](https://app.codacy.com/gh/Py-Contributors/AudioBook/pullRequest?prid=10418379) and [this](https://github.com/Py-Contributors/AudioBook/actions/runs/3303037027/jobs/5450537276) to locate your bugs and fix them.
You could also try and setup flake8 locally to have avoided the linting errors even before having raised the PR.

**Comment by codeperfectplus** [comment]
I have deeply reviewed the code, so the issue is you are creating the same variable name as imported from ODF.

try to change the text variable in line number 109, 111, 114, and 116. It will solve the issue. Suggested variable name `output_txt` or `odf_output`. you can also decide by yourself.

@Mr-vabs 
Install flake8 on your local and run the below flake8 command, the same command is running on the server.

```bash
pip install flake8
```
```bash
flake8 . --isolated --exclude=.cache,.venv,.svn,CVS,.bzr,.hg,.git,__pycache__,.tox,**/migrations/** --ignore=E203,W503,E501,F401
```

@hot9cups thanks for your feedback.

**Comment by hot9cups** [comment]
No problem @codePerfectPlus , happy to help.

**Review by DrakeEntity — APPROVED** [review]

**Pull request merged**
