### PR TITLE
Update on text highlight to main.py

### PR DESCRIPTION
**Pull request by TimTemi**
I have added a functionality to be able to highlight text

# Pull Request Template

**script name** -

**What have you Changed**

what you changed in the codebase.write here

### Self Check(Tick After Making pull Request)

- [x] This issue was assigned to me.
- [x] One Change in one Pull Request
- [x] My file is in proper folder
- [x] I am following clean code and Documentation and my code is well linted with flake8.
- [x] I have added README.md and requirements.txt with my script

If issue was not assigned to you Please don't make a PR. It will marked as invalid.

Join Us on Discord:- https://discord.gg/JfbK3bS

### CODE REVIEW

**Comment by TimTemi** [comment]
@codePerfectPlus , Pls ignore the commit I made 5 days ago, I have made my recent PR, pls check code and make updates.

**Comment by TimTemi** [comment]
@codePerfectPlus ,  I dropped a DM on the discord community.

**Comment by codeperfectplus** [comment]
@TimTemi I haven't received a message on the discord community.

**Comment by codeperfectplus** [comment]
It looks like you have created the solution for pdf files only as I previously mentioned we are not reading PDF files directly so it won't work.  first, we will convert the input book(pdf/txt/docs/epub/Mobi) into standard JSON format after that we can read it or save it.

**Comment by TimTemi** [comment]
@codePerfectPlus , Noted. I'll adjust it. Thanks

**Comment by TimTemi** [comment]
@codePerfectPlus , are you ''python_coder_028''?
A request is pending.

**Pull request closed without merging**
